### ISSUE TITLE
constant ::NIL is deprecated etc

### ISSUE THREAD

**Issue by benjbrandall** [hubsmoke/bro#73]
Any bro command after installation results in:

/var/lib/gems/2.5.0/gems/commander-4.1.5/lib/commander/user_interaction.rb:328: warning: constant ::NIL is deprecated
/var/lib/gems/2.5.0/gems/commander-4.1.5/lib/commander/user_interaction.rb:328: warning: constant ::Data is deprecated
/var/lib/gems/2.5.0/gems/commander-4.1.5/lib/commander/user_interaction.rb:328: warning: constant ::TRUE is deprecated
/var/lib/gems/2.5.0/gems/commander-4.1.5/lib/commander/user_interaction.rb:328: warning: constant ::FALSE is deprecated
/var/lib/gems/2.5.0/gems/commander-4.1.5/lib/commander/user_interaction.rb:328: warning: constant ::Fixnum is deprecated
/var/lib/gems/2.5.0/gems/commander-4.1.5/lib/commander/user_interaction.rb:328: warning: constant ::Bignum is deprecated

**Comment by benjbrandall** [comment]
No worries, this was solved earlier by commenting out line 328 of user_interaction.rb -- https://github.com/hubsmoke/bro/issues/67

**Comment by beigexperience** [comment]
I'm still getting this warning on bro 0.10 on debian buster.  It flashes for a split second before being scrolled out of view.

**Comment by azzarello** [comment]
> I'm still getting this warning on bro 0.1.0 on debian buster. It flashes for a split second before being scrolled out of view.

Bumping this, I am also experiencing this issue

**Comment by NerdyDeedsLLC** [comment]
Thirded! (M1 Silicon, Monterey 12.0.1)

Although, and just to be clear... @benjbrandall : were you suggesting that we implement that fix ourselves on our local builds?
